<?php
require_once 'config.php';

// Set response header to application/json
header('Content-Type: application/json');

// NOTE: The generate_uuid() function is REMOVED because the USERS table now uses AUTO_INCREMENT.

// Check for POST request method
if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    http_response_code(405);
    echo json_encode(['status' => 'error', 'message' => 'Method not allowed.']);
    exit;
}

// Get JSON data from request body
$json_data = file_get_contents("php://input");
$data = json_decode($json_data, true);

// Check if required fields are present
if (empty($data['username']) || empty($data['password']) || empty($data['email'])) {
    http_response_code(400);
    echo json_encode(['status' => 'error', 'message' => 'Missing required fields: username, password, or email.']);
    exit;
}

$username = $data['username'];
$password = $data['password'];
$email = $data['email'];

try {
    $conn = connectDB();

    // 1. Hash the password
    $password_hash = password_hash($password, PASSWORD_DEFAULT);
    $role = 'customer'; // Default role

    // Check if user or email already exists
    $stmt = $conn->prepare("SELECT id FROM USERS WHERE username = ? OR email = ?");
    $stmt->bind_param("ss", $username, $email);
    $stmt->execute();
    $stmt->store_result();

    if ($stmt->num_rows > 0) {
        http_response_code(409); // Conflict
        echo json_encode(['status' => 'error', 'message' => 'Username or email already exists.']);
        $stmt->close();
        $conn->close();
        exit;
    }
    $stmt->close();

    // Prepare SQL statement for insertion
    // We do NOT include 'id' in the column list.
    $sql = "INSERT INTO USERS (username, email, password_hash, role) VALUES (?, ?, ?, ?)";
    $stmt = $conn->prepare($sql);
    
    // Bind parameters: (username, email, password_hash, role)
    $stmt->bind_param("ssss", $username, $email, $password_hash, $role);

    if ($stmt->execute()) {
        $new_user_id = $conn->insert_id; // Get the ID automatically generated by MySQL
        
        http_response_code(201); // Created
        echo json_encode([
            'status' => 'success', 
            'message' => 'User registered successfully.', 
            'userId' => $new_user_id
        ]);
    } else {
        http_response_code(500);
        error_log("Database Error: " . $conn->error);
        echo json_encode(['status' => 'error', 'message' => 'Registration Error: ' . $conn->error]);
    }

    $stmt->close();
    $conn->close();

} catch (Exception $e) {
    http_response_code(500);
    error_log("General Error: " . $e->getMessage());
    echo json_encode(['status' => 'error', 'message' => 'Server Error: ' . $e->getMessage()]);
}
?>